### PR TITLE
Update nfs-ganesha to 2.7.1

### PR DESCRIPTION
**Pull request by joaocc**
Updating nfs-ganesha, in an attempt to address the apparently random crashes after long usage.
* https://github.com/kubernetes-incubator/external-storage/issues/762
* https://github.com/kubernetes-incubator/external-storage/issues/447

### CODE REVIEW

**Comment by wongma7** [comment]
/lgtm
/approve
however we need CLA

**Comment by wongma7** [comment]
@joaocc would you like me to tag a new release? 

I may have time to debug this from nfs-ganesha side of things in the near future but no guarantees there

**Comment by joaocc** [comment]
@wongma7 Yes, a new release would be great, so it could be deployed. Thx

**Comment by joaocc** [comment]
Great! Thanks a bunch!

**Pull request merged**
