### PR TITLE
Updated API Version, Added selector field.

### PR DESCRIPTION
**Pull request by zimmertr**

### CODE REVIEW

**Comment by zimmertr** [comment]
I'm unsure why `cla/linuxfoundation` is failing. I have:

1) Signed up for a Linux Foundation account.
2) Linked the Linux Foundation account to my this Github account.
3) Signed the CNCF Individual Contributor License Agreement.
4) Ensured that my [local](https://i.imgur.com/SJMuFug.png) git `user.name` and `user.email` are the same as what is on my [Github profile](https://i.imgur.com/oUYYHVV.png). Furthermore, as seen [here](https://i.imgur.com/3ALuV99.png) the Blue Question mark referenced in Step 2 of [this guide](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) do not appear for me. Inferring that it is, indeed, associated with my email and name. 

Please advise on what is necessary to get approved for this PR. Thank you!

**Comment by zimmertr** [comment]
I ran a `git commit --amend --reset-author` and it looks like it's accepting that I signed the contributor document now. However, the Travis CI configuration still seems malformed. I'd add a PR for that too but I'd have no idea what I'm doing 😄

**Comment by wongma7** [comment]
/lgtm
/approve
Thank you. Travis fails randomly sometimes, nothing to worry about.

**Comment by zimmertr** [comment]
@wongma7 I didn't realize at first that the deployment manifest is replicated in text in the Readme. I have opened a new PR to address that change here: https://github.com/kubernetes-incubator/external-storage/pull/1231

**Pull request merged**
