### PR TITLE
[cephfs-provisioner] Provisioner should not fail if secret exists

### PR DESCRIPTION
**Pull request by fcgravalos**
Fixes: https://github.com/kubernetes-incubator/external-storage/issues/1192

This will avoid cephfs provisioner to fail when recreating a PVC because the secret to provision it already exists.

cc/ @humblec

### CODE REVIEW

**Comment by fcgravalos** [comment]
@cofyc @childsb any chance you can take a look at this?

**Comment by fcgravalos** [comment]
@cofyc @childsb Any update?

**Comment by fcgravalos** [comment]
Any chance anyone will look at this?

**Comment by humblec** [comment]
@fcgravalos I will be on this soon :) . Apologies for the delay

**Comment by humblec** [comment]
@fcgravalos the PR looks good to me. I have one suggestion here, can you restrict my change to only `ceph` provisioners in this PR ? so that we are not sneaking another PR without others noticing it .

**Comment by fcgravalos** [comment]
@humblec pushed

**Comment by humblec** [comment]
@cofyc @wongma7 can any of you approve it ?

**Pull request merged**
