### PR TITLE
nfs-client: added support for arm64

### PR DESCRIPTION
**Pull request by snmagn**
Adding support in nfs-client-provisioner module for arm64 platform.

### CODE REVIEW

**Comment by snmagn** [comment]
please check me.
/assign @jsafrane

**Comment by kmova** [comment]
Hi @snmagn 

We are in the middle of migrating the NFS client code into a new home under  https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. The migration PR is up for review at the moment. https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2

Thank you for this PR and sorry to have kept you waiting here. Can I circle back with you to raise the PR again in the new repo after the migration is completed?

**Comment by snmagn** [comment]
Hi @kmova 
Thank you for your comment.
That project is interesting. I also want to help with this PR.
What kind of process do you need?

**Comment by nikhita** [comment]
As @kmova mentioned, we are in the process of archiving this repo and continuing work in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. Please reopen a PR in the new repo once https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2 has merged. Thanks for your patience! :) 

Going to close this PR in order to be able to archive this repo.

**Pull request closed without merging**
