### PR TITLE
Update nfs-client RBAC scripts

### PR DESCRIPTION
**Pull request by btannous**
- Fixed a typo for the OpenShift config
- Updated the scripts to be copy and paste-able.

### CODE REVIEW

**Comment by kmova** [comment]
Hi @btannous, thank you for catching these! We are in the middle of migrating the NFS client code into a new home under  https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. The migration PR is up for review at the moment. https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2

Would you like me to circle back with you for adding this change in the new repo once the migration PR is merged?

**Comment by btannous** [comment]
Thank you for the notification @kmova ! I subscribed to that PR and will check it out when it looks closed =)

**Comment by nikhita** [comment]
As @kmova mentioned, we are in the process of archiving this repo and continuing work in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. Please reopen a PR in the new repo once https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2 has merged. Thanks for your patience! :) 

Going to close this PR in order to be able to archive this repo.

**Pull request closed without merging**
