### PR TITLE
Make proper error messages in return paths.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@wongma7 Please review.

**Comment by wongma7** [comment]
this breaks heketi (temporarily) right? heketiBlockVolRes is never filled in

**Comment by humblec** [comment]
@wongma7 heketi mode is not operational. I can fill the essential members as I do with `default` hardcoded values. It does not make much sense though.  But I will be filling heketi response soon.

**Comment by wongma7** [comment]
okay yeah that makes sense. lgtm!

**Comment by humblec** [comment]
@wongma7  Thanks!

**Pull request merged**
