### PR TITLE
Update kube dependency to v1.13.2

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
```
Checking file snapshot/pkg/cloudprovider/providers/gce/gce_test.go
FAILED   /Users/travis/gopath/src/github.com/kubernetes-incubator/external-storage/repo-infra/verify/go-tools/verify-govet.sh	55s
make: *** [verify] Error 1
```
Go vet is passing locally for me , not sure why it fails on test infra. @wongma7 any pointers?

**Comment by humblec** [comment]
@wongma7 PTAL  :)

**Comment by erikh** [comment]
Is there anything I can do to expedite the integration and merge of this patch? I can't run dep on a source tree that contains 1.13 and a flexvolume provisioner because of the missing version package.

**Pull request closed without merging**
