### PR TITLE
relocate cephfs to ceph

### PR DESCRIPTION
**Pull request by rootfs**

### CODE REVIEW

**Comment by wongma7** [comment]
there is now 1.py thats intentional right?

Also can you rename (here or later) kubernetes.io/cephfs to something-else/cephfs, somebody brought up yesterday that using kubernetes.io can make Delete fail

**Comment by rootfs** [comment]
thanks, cleaned up now.

**Comment by wongma7** [comment]
lgtm, don't forget to rename the provisioner from kubernetes.io later! Gluster is using gluster.org, idk what we can use here for ceph

**Comment by rootfs** [comment]
yes, the name is renamed to `ceph`

**Pull request merged**
