### PR TITLE
Change error message and make it consistent across file.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@childsb Please review. Thanks !

**Comment by obnoxxx** [comment]
I feel this is kind of in response to PR #697.
I think we should first sort that PR out.
I am personally in favor of the `[...]` quoting.
IMHO it makes the error messages much more readable (for the human eye).

**Comment by humblec** [comment]
Thanks for the review.
~~~
 `I am personally in favor of the [...] quoting.
IMHO it makes the error messages much more readable (for the human eye).
~~~
Thats *not* the practice in entire kube source tree, thats why it was removed in between and I mentioned it in review comments. I will remove `error` string and do other correction mentioned here.

**Comment by obnoxxx** [comment]
> Thats not the practice in entire kube source tree, thats why it was removed in between and I mentioned it in review comments.

Hmm, we might still adopt it for our modules, since it makes log messages much more readable. (Easier to spot the relevant pieces.) That's what I was voting for.

>  I will remove error string and do other correction mentioned here in next iteration of the PR.

Thanks!

**Comment by obnoxxx** [comment]
ping

**Comment by wongma7** [comment]
closing for now, let me know if we still want this

**Comment by obnoxxx** [comment]
I think we still want to make the log messages consistent. (There was just the discussion about the "how".) Meanwhile pr #697 has adapted to @humblec 's proposed removal of `[...]`, so I'll withdraw my comments about that.

The other small nitpicks about making the messages really consistent still remain.

@humblec do you want to update the PR?

**Pull request closed without merging**
