### PR TITLE
nfs-client: added support for ppc64le [Power PC]

### PR DESCRIPTION
**Pull request by pratham-m**
Adding support in nfs-client-provisioner module for PowerPC (ppc64le) platform.

### CODE REVIEW

**Comment by pratham-m** [comment]
/assign @jsafrane @wongma7
kindly review

**Comment by kmova** [comment]
Hi @pratham-m @efussi = we are migrating the code for NFS client to https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. The migration PR is up for review at the moment. https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2

Would you like me to circle back with you to push this changes in after the above PR is merged?

**Comment by pratham-m** [comment]
> 
> 
> Hi @pratham-m @efussi = we are migrating the code for NFS client to https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. The migration PR is up for review at the moment. [kubernetes-sigs/nfs-subdir-external-provisioner#2](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2)
> 
> Would you like me to circle back with you to push this changes in after the above PR is merged?

@kmova yes sure. do let me know.

**Comment by nikhita** [comment]
As @kmova mentioned, we are in the process of archiving this repo and continuing work in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. Please reopen a PR in the new repo once https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2 has merged. Thanks for your patience! :) 

Going to close this PR in order to be able to archive this repo.

**Pull request closed without merging**
