### PR TITLE
fix issue 431

### PR DESCRIPTION
**Pull request by raffaelespazzoli**
this fixes issue 431:
https://github.com/kubernetes-incubator/external-storage/issues/431

/cc @wongma7 can you please merge ASAP?

### CODE REVIEW

**Comment by raffaelespazzoli** [comment]
@mtanino done.

**Comment by mtanino** [comment]
@raffaelespazzoli 
I believe comments on both kubernetes and openshift iscsi-provisioner-class.yaml need to be updated.
```
from
# portals: [192.168.99.101:3260]
to
# portals: 192.168.99.101:3260,192.168.99.111:3260
```

Can we pass [ or ] to portals?

**Comment by raffaelespazzoli** [comment]
@mtanino should be allright now. Thanks.

**Comment by mtanino** [comment]
lgtm. thanks.

**Pull request merged**
