### PR TITLE
Fix golint errors

### PR DESCRIPTION
**Pull request by xing-yang**
Fixes golint errors in snapshotter.go.

### CODE REVIEW

**Comment by xing-yang** [comment]
@rootfs @tsmetana @jingxu97

**Comment by xing-yang** [comment]
More golint fixes on the way.

**Comment by xing-yang** [comment]
This PR only fixed golint errors in snapshotter.go.  Another PR will be submitted soon to fix the golint errors in remaining files under the snapshot folder.

**Comment by rootfs** [comment]
lgtm, let's get all fixes and merge them together.

**Comment by xing-yang** [comment]
Sure, I'll submit another PR with this change in it.  I'm almost done.  Will abandon this one.

**Pull request closed without merging**
