### PR TITLE
explicitly use a versioned core client

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
use `client.CoreV1` instead of deprecated `client.Core`

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@rootfs I do not know how to trigger retest, this failure is not related.
```
Cannot find a valid baseurl for repo: base/7/x86_64
The command '/bin/sh -c rpm -Uvh https://download.ceph.com/rpm-$CEPH_VERSION/el7/noarch/ceph-release-1-1.el7.noarch.rpm &&   yum install -y epel-release &&   yum install -y --nogpgcheck ceph-common python-cephfs &&   yum clean all' returned a non-zero code: 1
make[1]: *** [quick-container] Error 1
make[1]: Leaving directory `/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/ceph/cephfs'
make: *** [ceph/cephfs] Error 2
The command "./test.sh" exited with 2.
```

**Comment by rootfs** [comment]
this is the trouble
```
Retrieving https://download.ceph.com/rpm-luminous/el7/noarch/ceph-release-1-1.el7.noarch.rpm
Preparing...                          ########################################
Updating / installing...
ceph-release-1-1.el7                  ########################################
Loaded plugins: fastestmirror, ovl
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
12: Timeout on http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
```

**Pull request merged**
