### PR TITLE
Update path creation and implemented possibility save data after removing PV  

### PR DESCRIPTION
**Pull request by BledaiOld**
Hello,

This PR resolved issue [#1339](https://github.com/kubernetes-incubator/external-storage/issues/1339).

In the scope of this PR was added the ability to use `metadate` (name, namespace, labels, annotations) PVC field for dynamical creation the pvPath and possibility saving data on nfs-storage after deletion PV.

Example:

*StorageClass*:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: kube-system
  name: managed-nfs-storage-test-2
provisioner: fuseim.pri/ifs 
parameters:
  archiveOnDelete: "false"
  pathPattern: "{pvc.namespace}/{pvc.name}"
  onDelete: "retain"
```

*PersistentVolumeClaim*:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: kube-system
  name: managed-nfs-storage-test-2
provisioner: fuseim.pri/ifs 
parameters:
  onDelete: "retain"
  pathPattern: "{pvc.namespace}/{pvc.name}"
```

### CODE REVIEW

**Comment by Bledai** [comment]
@k8s-ci-robot /check-cla

**Comment by Bledai** [comment]
@k8s-ci-robot /retest

**Comment by kmova** [comment]
@Bledai - thank you for this PR. 

We are in the middle of migrating the NFS client code into a new home under  https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. The migration PR is up for review at the moment. https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2

Can I request you to raise the PR on the new repo, once the above migration PR is closed? 

Thank you for working on this fix.

**Comment by Bledai** [comment]
> @Bledai - thank you for this PR.
> 
> We are in the middle of migrating the NFS client code into a new home under https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. The migration PR is up for review at the moment. [kubernetes-sigs/nfs-subdir-external-provisioner#2](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2)
> 
> Can I request you to raise the PR on the new repo, once the above migration PR is closed?
> 
> Thank you for working on this fix.

@kmova Thanks for your response.
Got it, I'm going to open PR for a new home after PR migrations will be merged.

**Comment by nikhita** [comment]
As @kmova mentioned, we are in the process of archiving this repo and continuing work in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. Please reopen a PR in the new repo once https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2 has merged. Thanks for your patience! :) 

Going to close this PR in order to be able to archive this repo.

**Pull request closed without merging**
