### PR TITLE
Add noauth support

### PR DESCRIPTION
**Pull request by j-griffith**
This adds the basic config checking for noauth and creates a service client appropriately.  This also requires an update to the glide version of gophercloud to a newer version that includes the newly added noauth package.

### CODE REVIEW

**Comment by aglitke** [comment]
@j-griffith I just tested this with my setup and it works well.  Could we push to get it merged?

**Comment by wongma7** [comment]
/area openstack/standalone-cinder

pls run `go get github.com/sgotti/glide-vc && glide-vc --use-lock-file`, it's just to minimize the amount of vendor code we check in. I will merge!

**Comment by j-griffith** [comment]
@wongma7 Ahh, thanks! I was wondering about the glide updates!!

**Comment by wongma7** [comment]
oops, glide-vc deleted the package we need :/

please edit the glide.lock file so it has the package: then do `glide install -v; glide-vc --use-lock-file` to get the noauth package again and prevent it from getting inadvertently deleted

```git
   subpackages:
   - openstack
   - openstack/blockstorage/extensions/volumeactions
+  - openstack/blockstorage/noauth
   - openstack/blockstorage/v2/snapshots
   - openstack/blockstorage/v2/volumes
   - openstack/common/extensions
```

(sorry for lack of docs around how we use glide, I am hoping we can move to golang/dep soon since that is supposed to be a much better experience)

**Comment by j-griffith** [comment]
Thanks @wongma7 I noticed the failure and was digging at Glide to try and fix that.  I actually was thinking of proposing an update to godep, but looks like that might take some coordination.  Anyway, thanks again!!

**Comment by klausenbusk** [comment]
Was `glide install -v; glide-vc --use-lock-file` run before this was merged?

Running `glide install -v; glide-vc --use-lock-file` on master, removes around ~ 60k lines of code in `vendor/github.com/gophercloud/gophercloud/openstack`, code which was added in this commit.

I'm only asking, because I'm vendoring `github.com/digitalocean/godo` in #470, and it seems a bit odd, that adding a new dependency removes ~ 75k lines.

**Comment by wongma7** [comment]
@klausenbusk appears not, oops. you are not doing anything wrong, your looks okay to me: perhaps I could do a separate PR just to run glide install -v; glide-vc --use-lock-file again but anyhow the repo will reach desired state eventually

**Comment by j-griffith** [comment]
@klausenbusk Sorry about that, @wongma7 actually pointed that out and I thought I had it sorted but it would appear I missed something upon the actual commit.  I've submitted https://github.com/kubernetes-incubator/external-storage/pull/471 to clean that up.

**Comment by klausenbusk** [comment]
> @klausenbusk Sorry about that

No problem :)

> I've submitted #471 to clean that up.

Thank, I will rebase when it has been merged.

**Pull request merged**
