### PR TITLE
Add namespace extended attributes to directory

### PR DESCRIPTION
**Pull request by pickledrick**
Add extended attribute to directory, this can be used for metrics/retention cleanup which I intend to contribute to this repository. The idea here is to build a relation for a directory to a namespace without the need for string parsing for unknown namespace names. i.e:

ns
ns-1
ns-1-dev

etc

### CODE REVIEW

**Comment by pickledrick** [comment]
Hi @wongma7 

Do you have any thoughts on this?

**Comment by pickledrick** [comment]
Hi @rootfs @wongma7,

let me know if there is any more required on this one?

**Comment by pickledrick** [comment]
@rootfs @wongma7 

I have rebased against glide.yaml to fix conflict. Are you able to add some input on this PR or merge?

**Comment by wongma7** [comment]
/lgtm
thank you and apologies for delay

**Pull request merged**
