### PR TITLE
ProvisionController support for SharedInformers

### LINKED ISSUE #546: ProvisionController support for SharedInformers
Hi,

I'd like to propose extending the [`ProvisionController`](https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/controller.go#L69) to optionally use [`SharedInformers`](https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go#L42) instead of "private" informers. This will support use-cases where other application components (e.g., the [`Provisioner`](https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/volume.go#L29) implementation) need to access PersistentVolumes / PersistentVolumeClaims / StorageClasses.

If this sounds relevant and reasonable, I'd be happy to work on that.

### PR DESCRIPTION
**Pull request by zcahana**
This PR adds support for running the `ProvisionController` with [`SharedInformers`](https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go#L42).

This is achieved by introducing a new constructor, `NewProvisionControllerWithConfig()` that enables to optionally pass in shared informers; The existing constructor, `NewProvisionController()`, as well as its behavior, are left as they were.

Resolves #546.

### CODE REVIEW

**Comment by zcahana** [comment]
@k8s-ci-robot I've signed the CLA.

**Comment by zcahana** [comment]
I've refactored the code to be consistent with the functional options pattern:
- Introduced 3 new option functions: `ClaimsInformer()`, `VolumesInformer()`, and `ClassesInformer()`,   
to be used with `NewProvisionController()`.
- Removed the `NewProvisionControllerWithConfig()` constructor mentioned in the beginning of this PR.

**Comment by zcahana** [comment]
@wongma7 did you get a chance to look at this?

**Comment by rootfs** [comment]
/assign @jsafrane 
wait till https://github.com/kubernetes-incubator/external-storage/pull/578 is resolved

**Comment by zcahana** [comment]
I've removed the commit which vendored the additional client-go/informers/* packages (as these were added as part of #578), and rebased.

**Comment by jsafrane** [comment]
/approve no-issue
Checking if there is merge bot...

**Pull request merged**
