### PR TITLE
Don't overwrite labels provided by user in snapshot object

### PR DESCRIPTION
**Pull request by disrani-px**
Issue #738 

/area snapshot
/assign @tsmetana

### CODE REVIEW

**Comment by cehoffman** [comment]
There is still an window in which user labels can be overwritten I think. The request to the api server needs to be a merge patch.

1. volumesnapshot created
2. snapshotter gets resource
3. user submits label merge patch
4. snapshotter commits updated volumesnapshot resource

In this setup the user labeling occurred in between the snapshotter getting and applying its work to the resource.

**Comment by disrani-px** [comment]
@cehoffman The update on the outdated object would fail since the resourceVersion in the stored object would have been newer than the object being updated. So the labels will not get removed. We will just try updating again with the newer version of the object.

More info on how this is handled in Kubernetes here: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#concurrency-control-and-consistency

**Comment by disrani-px** [comment]
@wongma7 @childsb Can this be merged?

**Pull request merged**
