### PR TITLE
Replace glog with klog

### PR DESCRIPTION
**Pull request by humblec**
Address #https://github.com/kubernetes-incubator/external-storage/issues/1105

    Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@wongma7 PTAL :).. Thanks !

**Comment by wongma7** [comment]
/lgtm
thanks
however needs a small rebase now :(

**Comment by humblec** [comment]
@wongma7 sure, done. Please merge it before I have to rebase again :)

**Pull request merged**
