### PR TITLE
Update nfs to lib 4 and client-go w GetReference fix

### PR DESCRIPTION
**Pull request by wongma7**
step 1 of resolving failing alpha suite https://github.com/kubernetes/kubernetes/issues/81403

Thanks to go modules + submodules, we can now update provisioners 1 by 1 :)

### CODE REVIEW

**Comment by wongma7** [comment]
/cc @jsafrane 
I'll probably need to self-lgtm.

**Comment by msau42** [comment]
You're not showing up as an approver?

**Pull request merged**
