### PR TITLE
refact(nfs-client): updates for external lib updates

### PR DESCRIPTION
**Pull request by wilmardo**
Since this PR: https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/46 has introduced some breaking changes I refactored the NFS client provisioner to be compatible.

This also removes the need to import `k8s.io/kubernetes/` which is advised against and has al kind of issues when using go modules:
https://github.com/kubernetes/kubernetes/issues/79384

Also switched to go modules to get the CI to complete since the `sigs.k8s.io/sig-storage-lib-external-provisioner` was missing and I did not want to enforce this on all clients.

Just tested it with my `lansible/nfs-client-provisioner:devel` image on my ARM64 cluster and it works as expected 🎉

### CODE REVIEW

**Comment by wilmardo** [comment]
Back to WIP for now since the CI is failing. Diving into the problem right now :)

**Comment by wilmardo** [comment]
Fixed! read_for_review 🎉 

Switched to go modules to get the CI to complete since I switched to the `sigs.k8s.io/sig-storage-lib-external-provisioner` package.

**Comment by wilmardo** [comment]
@jsafrane @wongma7 You guys got any time to look at this? This will impact future merge requests quite heavily so sooner merging == lesser rebasing :)

**Comment by lowang-bh** [comment]
all modue such as nfs, cephfs, glusterfs has to change the lib

**Comment by wilmardo** [comment]
@lowang-bh They should but that is not the scope of this PR. This PR should not impact any of the other clients :)

**Comment by kmova** [comment]
Hi @wilmardo, The NFS client code is being migrated to https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. The migration PR is up for review at the moment. https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2

Your changes look better in terms of supporting the go mod that what I did for the initial PR. Would you like me to circle back with you to push these changes in after the above PR is merged?

**Comment by wilmardo** [comment]
@kmova That would be fine, ping me as soon as the PR is merged. Then I will cherry-pick these changes to the new repo :)

**Comment by nikhita** [comment]
As @kmova mentioned, we are in the process of archiving this repo and continuing work in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. Please reopen a PR in the new repo once https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2 has merged. Thanks for your patience! :) 

Going to close this PR in order to be able to archive this repo.

**Pull request closed without merging**
