### PR TITLE
Updated nfs-client/readme.md with deployment steps

### PR DESCRIPTION
**Pull request by ShaneMalachow**
There was no documentation of the commands to run to actually deploy the edited yaml files.

### CODE REVIEW

**Comment by ShaneMalachow** [comment]
Signed CLA, sorry bout that

**Comment by wongma7** [comment]
is https://github.com/kubernetes-incubator/external-storage/pull/938 okay?

**Comment by ShaneMalachow** [comment]
#938 is still missing the actual commands to deploy the SC and Provisioner, but it does have good info. I can pull the changes and add the commands in again.

**Comment by wongma7** [comment]
sure, please do. thanks

**Pull request closed without merging**
