### PR TITLE
Pass in Snapshot spec to Create API

### PR DESCRIPTION
**Pull request by disrani-px**
Issue #640

### CODE REVIEW

**Comment by rootfs** [comment]
do you have a use case for passing the entire snapshot spec?

/assign @tsmetana

**Comment by disrani-px** [comment]
@rootfs Yes. Without this, there is no way to pass in additional options to the snapshot plugin. For example, in Portworx we can take different types of snaps, local snaps and cloud snaps. We can choose which one to take by passing in annotations in the spec.
Other drivers can also use this to pass in options similar to PVC specs.

**Comment by disrani-px** [comment]
@tsmetana PTAL. Thanks!

**Comment by tsmetana** [comment]
I understand the point. I would prefer to extend the existing mechanism: we already pass tags to the plugin. So far it's only the metadata created/updated during the snapshot creation. We may append the created tags with existing ones (created by the user in the VolumeSnapshot) and pass them all using the existing interface. Would that work for your use case?

**Comment by disrani-px** [comment]
@tsmetana Sure that would work for this case but in the future if there are other fields/options added to the snapshot spec that need to be passed in to the plugins it'll create the same problem again.

**Comment by tsmetana** [comment]
All right then.
/lgtm

**Comment by disrani-px** [comment]
@wongma7 Can you please merge this change. Thanks!

**Comment by harsh-px** [comment]
@wongma7 Can we get this merged?

**Comment by disrani-px** [comment]
@rootfs @tsmetana Can someone else help merge this change?

**Comment by disrani-px** [comment]
@childsb Can you please merge this change? Thanks!

**Pull request merged**
