### PR TITLE
Flexprovisoner use k8s.io/util/exec and Passing options parameters when provisioner/delete

### PR DESCRIPTION
**Pull request by fisherxu**
Flexprovisoner should use k8s.io/util/exec and Passing options parameters when provisioner/delete to the plugin, and alse add some new command to the example.

### CODE REVIEW

**Comment by childsb** [comment]
Thanks for the PR @fisherxu .. these changes look OK to me, but i'm going to wait for @wongma7 to give final review.

**Comment by fisherxu** [comment]
Kindly ping @wongma7 :)

**Comment by wongma7** [comment]
/lgtm

thanks, using the same flex driver call wrapping code as kubernetes makes sense to me.

**Pull request merged**
