### PR TITLE
Incorporating K8s api changes

### PR DESCRIPTION
**Pull request by kokhang**
Incorporating k8s API changes.
- Updating client-go and apimachinery version
- Importing K8S types from k8s.io/api
- Removing lib/helper and importing the kubernetes one instead temporary until helper go to k8s.io/util

### CODE REVIEW

**Comment by kokhang** [comment]
@wongma7 Kubernetes API and types are going through a lot of changes and i would like to keep up . This PR (still in WIP) makes sure that this project is compatible with Kubernetes 1.8 API changes.

I have split this  PR into two commits. One for the actual code changes and the other one is for vendor changes. Let me know what you think. I am still doing testing

**Comment by wongma7** [comment]
Thanks! please install and run also `glide-vc --use-lock-file` to avoid vendoring in all of k8s/k8s (among other things)

**Comment by kokhang** [comment]
@wongma7 I ran `glide-vc --use-lock-file` and submitted a PR. But right now the gometalinter is failing with. I didnt look deep into it but i didnt make any other changes other than the glide-vc call.
```
WARNING: vetshadow: no files to lint
WARNING: vet: no files to lint
```

**Comment by ianchakeres** [comment]
@kokhang & @wongma7 - I'm also seeing problems with gometalinter on my PRs: https://github.com/kubernetes-incubator/external-storage/pull/226 & https://github.com/kubernetes-incubator/external-storage/pull/225

**Comment by kokhang** [comment]
@wongma7 i think this is ready. PTAL when you have time.

**Comment by wongma7** [comment]
Thanks, it looks like we can get rid of my versioned helpers hack & just import kube directly (not so sure hack was needed to begin with...) 

@humblec do you see anything wrong with the heketi changes, iirc we had some manually patched changes that may be overwritten here? or is patch no longer needed?

**Comment by kokhang** [comment]
@wongma7 i did remove the private helpers.go and imported from kubernetes. I spoke to @caesarxuchao and he mentioned that helpers.go will go to k8s.io/api eventually but it will be done much later.

**Comment by caesarxuchao** [comment]
The planned move is tracked at https://github.com/kubernetes/kubernetes/issues/48209#issuecomment-314537745.

**Comment by wongma7** [comment]
@humblec heads up, I am merging. Might break heketi changes but it's easier to fix those than chnage this.

**Pull request merged**
