### PR TITLE
[glusterfs] Set permission correctly

### PR DESCRIPTION
**Pull request by yuanying**

### CODE REVIEW

**Comment by humblec** [comment]
@yuanying how did you verify or whats the source of this permission ?

**Comment by yuanying** [comment]
@humblec The directory which will be shared by glusterfs should be writable from user who has same GID of this directory. So I think we should provide access permission to GID.

**Comment by wongma7** [comment]
makes sense to me, what is the point in giving group ownership if group does not have full permissions

**Pull request merged**
