### PR TITLE
iscsi: clean up codes

### PR DESCRIPTION
**Pull request by nak3**
This patch includes:
 - removed unnecessary code comments
 - updated start sub command help message.

### CODE REVIEW

**Comment by raffaelespazzoli** [comment]
I'm fine with this change

**Comment by wongma7** [comment]
needs rebase, also this can be cleaned up too 👍 
iscsi/targetd/provisioner/iscsi-provisioner.go:76:1:warning: result is unused (deadcode)

**Comment by nak3** [comment]
Thank you. Updated.

**Pull request merged**
