### PR TITLE
Move lib to https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner

### PR DESCRIPTION
**Pull request by wongma7**
Delete lib directory.

### CODE REVIEW

**Comment by iawia002** [comment]
Some files in `sig-storage-lib-external-provisioner` are not the latest version

**Comment by wongma7** [comment]
@iawia002 oops, should be fixed now, thanks!

**Comment by wongma7** [comment]
@childsb @jsafrane PTAL . Is putting a "deprecation notice" in lib/README.md sufficient or should I remove all of lib?

**Comment by warmchang** [comment]
Hi @wongma7 
Does the document deleted by [commit](https://github.com/kubernetes-incubator/external-storage/pull/1026/commits/317d76b34997b5671a4cd0bfb31fae41338fdde9) have been transferred to [sig-storage-lib-external-provisioner repo](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner)?

**Pull request merged**
