### PR TITLE
fix on openshift  Permission denied

### PR DESCRIPTION
**Pull request by helingjun**

### CODE REVIEW

**Comment by cofyc** [comment]
I suggest you use [ceph-csi](https://github.com/ceph/ceph-csi) instead.

**Comment by helingjun** [comment]
add cla

**Comment by humblec** [comment]
@helingjun as @cofyc suggested its better to use csi. We are no longer planning to maintain these provisioners so the suggestion.

**Comment by helingjun** [comment]
Think you

**Comment by helingjun** [comment]
I signed it

**Pull request closed without merging**
