### PR TITLE
Add DigitalOcean provisioner

### PR DESCRIPTION
**Pull request by klausenbusk**
This commit add a DigitalOcean provisioner and a flexvolume plugin
for DigitalOcean.

---

Finally, here we go :) The code has only been tested slightly on my k8s 1.8 cluster.

I'm not sure if I did the vendoring correctly ~~(`glide get github.com/digitalocean/godo` + `glide-vc --use-lock-file`)..~~ ~~**Edit:** See commit message~~ [solved](https://github.com/kubernetes-incubator/external-storage/pull/449#issuecomment-345476921)

/cc @andrewsykim

### CODE REVIEW

**Comment by andrewsykim** [comment]
cc @odacremolbap

**Comment by klausenbusk** [comment]
Ready for review, CI is green and the vendoring "issue" has been solved. The Go flexvolume plugin is maybe a big ugly, but it gets the job done..

**Comment by wongma7** [comment]
/lgtm

I will create quay.io/kubernetes_incubator/digitalocean-flexplugin and quay.io/kubernetes_incubator/digitalocean-provisioner and give you write permissions to them after we merge.

Thanks & sorry for the delay :)

**Comment by klausenbusk** [comment]
> /lgtm

Great, I will rebase and remove the `REVERT` commit when I get home..

**Comment by klausenbusk** [comment]
> Great, I will rebase and remove the REVERT commit when I get home..

Done and ready for merge :)

**Comment by klausenbusk** [comment]
@wongma7 are we waiting on anything? or maybe I'm just a bit impatient..

**Comment by klausenbusk** [comment]
```
 - [ ] Prevent k8s from scheduling more than 5 disks to a single droplet 
```
Probably solvable when [`Topology Aware Volume Scheduling`](https://github.com/kubernetes/features/issues/490) get implemented.

**Comment by msau42** [comment]
I think for solving the max count scheduling issue, you're looking for a generalized version of kubernetes/kubernetes#53461

**Comment by klausenbusk** [comment]
> I think for solving the max count scheduling issue, you're looking for a generalized version of kubernetes/kubernetes#53461

Interesting (but mostly related to internal volume plugin, it seems (?)), I will play around with whatever gets implemented first. `MatchUnboundPVCs` seems to provide enough functionality to implement à `Volume Count Predicate` like the internal volume plugin.

https://github.com/kubernetes/kubernetes/issues/24317 also contain a few ideas.

**Comment by msau42** [comment]
The comments in the PR suggest an alternative using ConfigMaps to better support out of tree cloud providers.

**Comment by klausenbusk** [comment]
Thanks @wongma7 Do you have time to create quay.io/kubernetes_incubator/digitalocean-provisioner and quay.io/kubernetes_incubator/digitalocean-flexplugin ? :)

**Comment by wongma7** [comment]
@klausenbusk yes, I have sent you an invite also

Still trying to sort out and document how we should do versioning/release/auto-push for the repo, atm it needs a git tag to trigger build&push but that's not ideal. will create a github issue later.

**Comment by klausenbusk** [comment]
> @klausenbusk yes, I have sent you an invite also

Great! I have just pushed both image as: `quay.io/external_storage/digitalocean-provisioner:latest` and `quay.io/external_storage/digitalocean-provisioner:latest`. The registry in the `Makefile` wasn't correct, so I have opened a PR to fix that: https://github.com/kubernetes-incubator/external-storage/pull/520
BTW: It seems like I also forgot to add the provisioner to the `Makefile`, will do that later.

> Still trying to sort out and document how we should do versioning/release/auto-push for the repo, atm it needs a git tag to trigger build&push but that's not ideal. will create a github issue later.

For now I'm just pushing as `:latest`, but it would be more ideal pushing with a version number, so backwards incompatible changes doesn't break a running cluster. Hmm...

**Pull request merged**
