### PR TITLE
Revert changes in PR#1114

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by Paxa** [comment]
I'm facing same issue. Surprisingly tests still working

**Comment by ticpu** [comment]
/approve

It also breaks here if I use make container and deploy.

**Comment by humblec** [comment]
@wongma7 @childsb @jsafrane can you please review this asap ?

**Comment by leobuzhi** [comment]
👍

**Comment by wongma7** [comment]
/lgtm
/approve

glog->klog migration needs to happen repowide. Annoying.

**Comment by zhangxpp** [comment]
Dear, 

After reverting to 1114, I is facing the following error when executing rdb-provisioner.   Is it an expected behavior ?  Thanks a lot. 

# docker run -ti 2ef1dc4031a5 
F1113 06:28:58.006224       1 main.go:57] Failed to create config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
goroutine 1 [running]:
github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog.stacks(0xc00030ec00, 0xc000318000, 0xb0, 0x105)
	/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog/klog.go:828 +0xb8
github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog.(*loggingT).output(0x1f19d80, 0xc000000003, 0xc00030a850, 0x1e80b0e, 0x7, 0x39, 0x0)
	/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog/klog.go:779 +0x351
github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog.(*loggingT).printf(0x1f19d80, 0x3, 0x136577a, 0x1b, 0xc000137f20, 0x1, 0x1)
	/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog/klog.go:678 +0x14b
github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog.Fatalf(...)
	/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog/klog.go:1207
main.main()
	/go/src/github.com/kubernetes-incubator/external-storage/ceph/rbd/cmd/rbd-provisioner/main.go:57 +0x18a

**Pull request merged**
