### PR TITLE
ceph/rbd: look up monitor hostnames in cluster DNS

### PR DESCRIPTION
**Pull request by dmick**
Allow rbd to be provisioned with monitors pointing to cluster-local
DNS names, like "ceph-mon.ceph.svc.cluster.local", without requiring
Kubernetes host to be configured to search that domain

### CODE REVIEW

**Comment by dmick** [comment]
Well *that* was a fight.  There's a lot of unrelated updates in here, but I did it using an extension to the documented procedure: 

1) add a new dependency with glide add
2) run glide update
3) run glide-vc --use-lock-file
4) manually git add all the changes created the above

**Comment by rootfs** [comment]
they are excessive 

@wongma7 @pospispa any more tricks?

**Comment by dmick** [comment]
I mean..the reason they're updated is because glide didn't version-lock them, so there are now new versions

**Comment by pospispa** [comment]
I also struggled with `glide` several times and I don't have any `glide` tricks in my hat.
I personally use [`unittests.sh`](https://github.com/kubernetes-incubator/external-storage/blob/master/unittests.sh) to check whether all unit tests still pass after a "massive" glide update.

**Comment by dmick** [comment]
@pospispa: well that failed immediately (sigh):

Running unit tests in ./openebs/pkg/v1
# github.com/kubernetes-incubator/external-storage/openebs/pkg/v1
./maya_api_test.go:140: too many arguments in call to EvaluateCreateVolume
	have (OpenEBSVolumeTest, string, string)
	want (OpenEBSVolumeInterface, "github.com/kubernetes-incubator/external-storage/openebs/types/v1".VolumeSpec)
FAIL	github.com/kubernetes-incubator/external-storage/openebs/pkg/v1 [build failed]

**Comment by dmick** [comment]
However: 
$ ./unittests.sh

Running unit tests in ./nfs/pkg/volume
# github.com/kubernetes-incubator/external-storage/lib/controller
../../../lib/controller/controller.go:582: cannot use claim (type *"github.com/kubernetes-incubator/external-storage/vendor/k8s.io/api/core/v1".PersistentVolumeClaim) as type *"github.com/kubernetes-incubator/external-storage/vendor/k8s.io/kubernetes/vendor/k8s.io/api/core/v1".PersistentVolumeClaim in argument to helper.GetPersistentVolumeClaimClass
../../../lib/controller/controller.go:752: cannot use claim (type *"github.com/kubernetes-incubator/external-storage/vendor/k8s.io/api/core/v1".PersistentVolumeClaim) as type *"github.com/kubernetes-incubator/external-storage/vendor/k8s.io/kubernetes/vendor/k8s.io/api/core/v1".PersistentVolumeClaim in argument to helper.GetPersistentVolumeClaimClass
FAIL	github.com/kubernetes-incubator/external-storage/nfs/pkg/volume [build failed]


This is starting to seem like a pretty challenging repo for external contributors.

**Comment by pospispa** [comment]
Well, IMHO, the `glide update` is the challenge.

I personally did an ugly hack [here](https://github.com/kubernetes-incubator/external-storage/pull/524/commits/0c90bb3647d150d01a636b9574baad586bca9c61) and I hope @wongma7 will help me to add the needed packages in correct way.

**Comment by dmick** [comment]
Yes, but the glide update is required when one adds a dependency, and if no one is making projects 1) run tests and/or 2) lock versions....

**Comment by dmick** [comment]
So, if I were to pursue this PR...is it on me to identify which versions every alien plugin *should* have locked, and supply the locking?  Or how is it expected that we move forward together?

**Comment by pospispa** [comment]
> So, if I were to pursue this PR...is it on me to identify which versions every alien plugin should have locked, and supply the locking? Or how is it expected that we move forward together?

@wongma7 please, can you advice?

@dmick and myself have run into the same problem with `glide update` and vendor package locking.

I did some hacks [here](https://github.com/kubernetes-incubator/external-storage/pull/524/commits/f4184e2550bbcee5ce3d33770c81af4d6ca2c634) and [here](https://github.com/kubernetes-incubator/external-storage/pull/524/commits/79bf7a7578f627feea19f08be609fe68f169b5c6) and [here](https://github.com/kubernetes-incubator/external-storage/pull/524/commits/0c90bb3647d150d01a636b9574baad586bca9c61) that only postone solution of the vendor package locking problem.

**Comment by wongma7** [comment]
hey @dmick sorry for the troubles and slow response, sure the additions are excessive in the sense that some are not strictly relevant to the PR, but as far as I can tell, they are unavoidable meaning it's fine and you did everything correctly. There is no easy way to update or add a *single* package with glide (afaik?!?) since it needs to do whatever it's doing, reconcile the dependency graph etc., as part of a `glide up` so unfortunately we have to deal with potentially dozens of packages getting updated every time we want to make changes to just one or two. Afaik this is an issue for any project that checks in its vendor directory, but sure for us it's exacerbated. The "Go people" promised they'd fix dependency management this year so hopefully that happens :))

Since the code changes themselves, the part that actually matters, are good, and teh vendor changes are fine to me, let's merge.

/lgtm

**Comment by wongma7** [comment]
oops, @rootfs can you review the code? thought it was already marked good and only vendor problem outstanding, but still needs review.

**Comment by dmick** [comment]
...but this will absolutely break other plugins.

**Comment by wongma7** [comment]
why's that? Tests are green, at least :)

**Comment by dmick** [comment]
https://github.com/kubernetes-incubator/external-storage/pull/537#issuecomment-356391241  travis doesn't run the unit tests that unittests.sh does

**Comment by wongma7** [comment]
I see, I tried running  that test locally and it passed, plus this PR doesn't touch either k8s.io/api/ nor k8s.io/kubernetes so it must be some kind of fluke. as long as tests are green we should be confident we didn't berak any other code, it seems openebs is the exception here as I neglected to add it to travis

**Comment by dmick** [comment]
Got it.  I'm rerunning unittests.sh without openebs and it's passing now too.  I guess I had a confused vendor/ state.

**Comment by dmick** [comment]
Are we gonna merge this?

**Comment by rootfs** [comment]
cc @childsb

**Comment by dmick** [comment]
:thumbsup:

**Pull request merged**
