### PR TITLE
Improves the README.md for nfs-client

### PR DESCRIPTION
**Pull request by cdrage**
This commit elaborates on how to deploy nfs-client as well as modify and
doing changes to the files before said deployment, updating the
README.md to make deployment easier.

### CODE REVIEW

**Comment by cdrage** [comment]
ping @wongma7 @jackielii

**Comment by jackielii** [comment]
Looks good to me. Thanks!

**Comment by cdrage** [comment]
Closes https://github.com/kubernetes-incubator/external-storage/issues/652

**Comment by cdrage** [comment]
ping @wongma7

**Comment by cdrage** [comment]
Ping @wongma7 @ianchakeres @salkin could I get this reviewed / merged?

**Comment by wongma7** [comment]
/lgtm
thank you

**Pull request merged**
