### PR TITLE
Update CEPH_VERSION to nautilus

### PR DESCRIPTION
**Pull request by hswong3i**
Also see #841

### CODE REVIEW

**Comment by MatthiasHertel** [comment]
why not merged ?

**Comment by ahmadalli** [comment]
@hswong3i is it possible to fix build issues?

**Comment by hswong3i** [comment]
> @hswong3i is it possible to fix build issues?

From https://travis-ci.org/kubernetes-incubator/external-storage/jobs/577084551#L7940

```
# k8s.io/client-go/transport

../client-go/transport/round_trippers.go:70:11: cannot convert klog.V(9) (type klog.Verbose) to type bool

../client-go/transport/round_trippers.go:72:11: cannot convert klog.V(8) (type klog.Verbose) to type bool

../client-go/transport/round_trippers.go:74:11: cannot convert klog.V(7) (type klog.Verbose) to type bool

../client-go/transport/round_trippers.go:76:11: cannot convert klog.V(6) (type klog.Verbose) to type bool

2019/09/03 01:52:28 e2e.go:77: err: go get -u k8s.io/test-infra/kubetest: exit status 2
```

Which should coming from `vendor/k8s.io/client-go/transport/round_trippers.go` and not directly related to Ceph related?

**Comment by hswong3i** [comment]
@cofyc @ahmadalli build now passed after rebase, shouldn’t belongs to Ceph related code issue ;-)

**Comment by hswong3i** [comment]
@rootfs @cofyc could we have a /lgtm again?

**Pull request merged**
