### PR TITLE
nfs-client: adding support for s390x

### PR DESCRIPTION
**Pull request by namrata-ibm**
This PR includes:
* Enabling s390x builds in Travis
* Deploying image for s390x to Registry through Travis builds

### CODE REVIEW

**Comment by namrata-ibm** [comment]
I signed CLA

**Comment by namrata-ibm** [comment]
@wongma7 @jsafrane @cofyc could you please have a look?

**Comment by namrata-ibm** [comment]
Any updates on this?

**Comment by namrata-ibm** [comment]
@wongma7 @jsafrane @cofyc could you please check?

**Comment by kmova** [comment]
Hi @namrata-ibm. 

We are in the middle of migrating the NFS client code into a new home under  https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. The migration PR is up for review at the moment. https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2

Thank you for this PR and your patience. Can I circle back with you to push these changes into the new repo once the above migration PR is closed?

**Comment by namrata-ibm** [comment]
Thank you @kmova for getting back, Please let me know when the new repo is ready to pull these changes.

**Comment by nikhita** [comment]
As @kmova mentioned, we are in the process of archiving this repo and continuing work in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner. Please reopen a PR in the new repo once https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/2 has merged. Thanks for your patience! :) 

Going to close this PR in order to be able to archive this repo.

**Pull request closed without merging**
