### PR TITLE
gluster/block: remove redundant code comments

### PR DESCRIPTION
**Pull request by obnoxxx**
Comments that repeat exactly what is spelled out in code
in the next line are not helpful and should be avoided.

Signed-off-by: Michael Adam <obnox@redhat.com>

### CODE REVIEW

**Comment by obnoxxx** [comment]
@wongma7, @humblec - please take a look!

**Comment by obnoxxx** [comment]
@jsafrane - ptal

**Comment by obnoxxx** [comment]
any comments? :-)

**Comment by humblec** [comment]
@wongma7 can you please merge this PR ?

**Pull request merged**
