### PR TITLE
Add missing ports and NFSv3 Support

### PR DESCRIPTION
**Pull request by kvaps**
This PR is sticking `nlockmgr`, `rquotad` and `statd` to use static ports, and describes all of them in Kubernetes manifests.

This change allows to use NFSv3 protocol which is stateless and better survives when network crashes and nfs-server pod restarts.

```
# rpcinfo -p
   program vers proto   port  service
    100000    4   tcp    111  portmapper
    100000    3   tcp    111  portmapper
    100000    2   tcp    111  portmapper
    100000    4   udp    111  portmapper
    100000    3   udp    111  portmapper
    100000    2   udp    111  portmapper
    100003    3   udp   2049  nfs
    100003    3   tcp   2049  nfs
    100005    1   udp  20048  mountd
    100005    1   tcp  20048  mountd
    100005    3   udp  20048  mountd
    100005    3   tcp  20048  mountd
    100003    4   udp   2049  nfs
    100003    4   tcp   2049  nfs
    100021    4   udp  32803  nlockmgr
    100021    4   tcp  32803  nlockmgr
    100011    1   udp    875  rquotad
    100011    1   tcp    875  rquotad
    100011    2   udp    875  rquotad
    100011    2   tcp    875  rquotad
    100024    1   udp    662  status
    100024    1   tcp    662  status
```

### CODE REVIEW

**Comment by kvaps** [comment]
/assign @wongma7 

Do we need `setNlmPort` and `setRquotaPort` methods for update existing config?

**Comment by wongma7** [comment]
Thanks for this, I've had quite some troubles using ganesha NFS 4.x personally so opening up 3.x can't hurt...
/lgtm
/approve

> Do we need setNlmPort and setRquotaPort methods for update existing config?

Rquota_Port defaults to 875 so it shouldn't be needed https://github.com/nfs-ganesha/nfs-ganesha/blob/86de5d6746a83023566e0838b2e55dbdcce4c4df/src/config_samples/config.txt#L43.

setNlmPort might be needed since it defaults to random, but you can add it in a follow-up PR if you like.

**Comment by kvaps** [comment]
Hi @wongma7, I've added function for setting NLM_Port line.
PR is ready to merge.

**Comment by wongma7** [comment]
There are some failing test cases which test that the service has only 2049 and 111 ports. https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/pkg/volume/provision_test.go#L676

Could you move the declaration of `expectedPorts` to the package level so that we can find+replace `[]endpointPort{{2049, v1.ProtocolTCP}, {20048, v1.ProtocolTCP}, {111, v1.ProtocolUDP}, {111, v1.ProtocolTCP}})` with `expectedPorts`? Then as long as `go test ./pkg/...` passes we are good.

**Comment by kvaps** [comment]
Sure, job is done!

**Comment by wongma7** [comment]
/lgtm
/approve

Thanks, nice work

**Comment by kvaps** [comment]
Hi @wongma7, I've created PR for update nfs-server-provisioner helm-chart https://github.com/helm/charts/pull/19260
Can we prepare docker image with this change?

**Comment by cedricve** [comment]
@wongma7 looks like people need more builds.. If we want to have these people stay involved with open source project. We expect some help from the owners as well. 

@kvaps and @naseemkullah just did an amazing job here, but no one can use it. This doesn't feel right.

**Comment by wongma7** [comment]
Yes, this project needs a new home and maintainer as releases being blocked by my availability/ability to execute the manual release steps is not sustainable. See https://github.com/kubernetes/org/issues/1563

**Pull request merged**
