### PR TITLE
nfs-client add parameters to control target dirs.

### PR DESCRIPTION
**Pull request by iineva**
For some reason we need target dir static.
This PR is implement this feature.

### CODE REVIEW

**Comment by wongma7** [comment]
Nice, I think something like this has been requested a number of times and I've just told people to create PVs manually. But this is an acceptable middle-ground, it saves them time...

Awaiting CLA

**Comment by iineva** [comment]
> Nice, I think something like this has been requested a number of times and I've just told people to create PVs manually. But this is an acceptable middle-ground, it saves them time...
> 
> Awaiting CLA

You can use this image`ineva/nfs-client-provisioner:latest`  to  replace `quay.io/external_storage/nfs-client-provisioner` to user this features.

**Comment by iineva** [comment]
CLA done!

**Comment by yashbhutwala** [comment]
ping on status of this 😄

**Comment by wongma7** [comment]
I think archiveDoNotMove makes things quite confusing. archiveOnDelete was already a bit confusing because "archiving" a directory instead of actually deleting it is non-standard behavior. Basically there are 2 flags and 3 possibilities on PVC deletion:
1. Delete directory archiveOnDelete false
2. "Archive" directory archiveOnDelete true and archiveDoNotMove false
3. Keep directory archiveOnDelete true and archiveDoNotMove true

Could we introduce a new parameter that makes this clear and deprecate archiveOnDelete? Like deletionBehavior that accepts (delete, archive, keep)?

**Pull request closed without merging**
