### PR TITLE
Fix issue 149 - nfs-client-provisioner create folder with 755, not 777

### PR DESCRIPTION
**Pull request by KinOSurvival**
REF:
https://github.com/kubernetes-incubator/external-storage/issues/149

### CODE REVIEW

**Comment by KinOSurvival** [comment]
CLA signed

**Comment by wongma7** [comment]
Please set your email to match github's, then cla should work https://help.github.com/articles/setting-your-email-in-git/.

code lgtm, thanks!

**Comment by wongma7** [comment]
mm merging, CLA is signed the issue is just that the commit was not made with same email as GitHub account's. Thanks again!

**Comment by ianchakeres** [comment]
@KinOSurvival - I earlier ran into a similar issue related to the CLA and commit email address- here's some advice on how to deal with it - https://medium.com/salesforce-engineering/contributing-to-open-source-at-work-step-1-corporate-cla-7cf74eb77b87

**Pull request merged**
