### PR TITLE
make the fsid device setting configurable

### PR DESCRIPTION
**Pull request by thirdeyenick**
This makes the fsid_device setting configurable. To not affect already deployed nfs provisioners I did not change the default to `false`. This should solve issue https://github.com/kubernetes-incubator/external-storage/issues/1212.

### CODE REVIEW

**Comment by thirdeyenick** [comment]
I signed it

**Comment by wongma7** [comment]
Thx for prs. I’m looking into why e2e is not building/running, it worked a few days ago.

**Comment by wongma7** [comment]
/lgtm
/approve
thanks again.

**Comment by cedricve** [comment]
@thirdeyenick cool, having the same issue. Would you have an example yaml file, which shows how to use it?

**Comment by cedricve** [comment]
@thirdeyenick sorry to disturb, but still looking around a fix, as this hasn't been merged into the  helm repo (https://github.com/helm/charts/issues/18965).  I was wondering how you fixed it. Any help is more than welcome! Super thanks Nick.

**Comment by cedricve** [comment]
@wongma7 any chance a new release would be made for this? Thanks!

**Pull request merged**
