### PR TITLE
Update go version to 1.9

### PR DESCRIPTION
**Pull request by max8899**
Update go version to 1.9 since kubernetes already use the latest go version.

### CODE REVIEW

**Comment by ianchakeres** [comment]
@max8899 @wongma7 - If these locations are updated to `go 1.9`, should the [travis ci build go](https://github.com/kubernetes-incubator/external-storage/blob/master/.travis.yml#L3) also be updated?

**Comment by max8899** [comment]
@ianchakeres thanks for reminding, changed it to 1.9.3.

**Comment by max8899** [comment]
@ianchakeres @wongma7 Any updates? It's not a big change, but the progress is slow.

**Comment by wongma7** [comment]
Yes it is slow, 1.10 is out, apologies :). Please fix conflicts, maybe change it to 1.10, & put the variables renames in a separate PR

**Comment by max8899** [comment]
#826

**Pull request closed without merging**
