### PR TITLE
Bump golang version to 1.10.3

### PR DESCRIPTION
**Pull request by max8899**
fix the problem in pr: [#719](https://github.com/kubernetes-incubator/external-storage/pull/719)

### CODE REVIEW

**Comment by wongma7** [comment]
```
Verifying /home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/repo-infra/verify/go-tools/verify-gometalinter.sh
local-volume/utils/update-helm-values-pre-v2.2.0/main.go:25:2:error: cannot find package "github.com/kubernetes-incubator/external-storage/local-volume/utils/update-helm-values/pkg/chartutil" in any of: (vet)
local-volume/utils/update-helm-values-pre-v2.2.0/main.go:25:2:warning: cannot find package "github.com/kubernetes-incubator/external-storage/local-volume/utils/update-helm-values/pkg/chartutil" in any of: (vetshadow)
FAILED   /home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/repo-infra/verify/go-tools/verify-gometalinter.sh	1s
Verifying /home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/repo-infra/verify/go-tools/verify-govet.sh
local-volume/utils/update-helm-values-pre-v2.2.0/main.go:25:2: cannot find package "github.com/kubernetes-incubator/external-storage/local-volume/utils/update-helm-values/pkg/chartutil" in any of:
	/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/vendor/github.com/kubernetes-incubator/external-storage/local-volume/utils/update-helm-values/pkg/chartutil (vendor tree)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/github.com/kubernetes-incubator/external-storage/local-volume/utils/update-helm-values/pkg/chartutil (from $GOROOT)
	/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/local-volume/utils/update-helm-values/pkg/chartutil (from $GOPATH)
FAILED   /home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/repo-infra/verify/go-tools/verify-govet.sh	1s
```
strange error, @cofyc is the author of the helm updater if you get a chance can you see what is happening? thanks for all your help

**Comment by max8899** [comment]
@wongma7 there are too many problems in travis ci and vendor packages, I'll open another pr to fix the existing problem on master and then do this pr again

**Comment by wongma7** [comment]
@max8899 do you have any WIP I can continue working off of? I'm working on cleaning up travis and vendor now at https://github.com/kubernetes-incubator/external-storage/pull/846

**Comment by max8899** [comment]
@wongma7 will continue to work on this one from this weekend. :)

**Comment by wongma7** [comment]
I copied some of your changes into https://github.com/kubernetes-incubator/external-storage/pull/846 and merged it, I'm still not sure about the helm thing though. It seems to me the travis tests are not deterministic, I change one thing somewhere and then it complains about some other code that hasn't changed in a year

**Pull request closed without merging**
